#ifndef SHIPS_CONFIG_H
#define SHIPS_CONFIG_H

#define SRV_UID 42

#define SRV_PORT_RANGE_START 43001
#define SRV_PORT_RANGE_END 43200

#define CLIENT_PORT_RANGE_START 41001
#define CLIENT_PORT_RANGE_END 41050

#define CLIENT_TIMEOUT 5000

#define SRV_BROADCAST_INTERVAL 5000

#endif //SHIPS_CONFIG_H
